<a href="https://colab.research.google.com/github/huiminPark/huimin/blob/main/Colab_Notebooks/04w_array_stack_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b = np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
x = np.array([1,2,3])
y = np.array([5,6,7])
np.vstack((x,y))

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b = np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [ ]:
x = np.array([1,2,3])
y = np.array([5,6,7])
np.column_stack((x,y))

array([[1, 5],
       [2, 6],
       [3, 7]])

In [ ]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [ ]:
np.hstack((x,y))

array([1, 2, 3, 5, 6, 7])

In [ ]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b = np.arange(10,22).reshape(4,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [ ]:
np.row_stack((a,b))

/tmp/ipykernel_215/1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [ ]:
a = np.array([1,2])
b = np.array([3,4])
c = np.array([5,6])

In [ ]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a,b,c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a,b,c), axis = None)

array([1, 2, 3, 4, 5, 6])

In [ ]:
x = np.arange(6).reshape(2,3)
x
y = np.arange(10,16).reshape(2,3)
y
z = np.arange(20,24).reshape(2,2)
z

array([[20, 21],
       [22, 23]])

In [ ]:
np.concatenate((x,y), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [ ]:
np.concatenate((x,y,z), axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [ ]:
np.concatenate((x,y), axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

In [ ]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
b = np.array([4,5,6])
b

array([4, 5, 6])

In [ ]:
np.stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.stack((a,b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.stack((a,b), axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.arange(1,19).reshape(3,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [ ]:
np.arange(16).reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
y = np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
z = np.arange(20,26).reshape(2,3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [ ]:
ax1 = np.stack((x,y,z), axis= 1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [ ]:
ax1.shape

(2, 3, 3)

In [ ]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
y = np.arange(10,16).reshape(2,3)
y


array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
z = np.arange(20,26).reshape(2,3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [ ]:
ax2 = np.stack((x,y,z), axis=2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [ ]:
ax2.shape

(2, 3, 3)

In [ ]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
c= np.arange(1,6,2)
c


array([1, 3, 5])

In [ ]:
np.hstack((a, np.expand_dims(c, axis=1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
np.column_stack((a,c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

##

In [ ]:
b = np.arange(1,5)
b

array([1, 2, 3, 4])

In [ ]:
np.row_stack((a,b))

/tmp/ipykernel_215/1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [ ]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])
x

array([[1, 2, 3]])

In [ ]:
y

array([[4, 5, 6]])

In [ ]:
x.shape, y.shape

((1, 3), (1, 3))

In [ ]:
np.column_stack((x,y))

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
np.c_[x,10,20,y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [ ]:
np.column_stack([x,10,20,y])

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.row_stack((a,b))

/tmp/ipykernel_215/1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.r_[a,0,0,b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [ ]:
np.r_[3:10:3, [0]*2,5,6]

array([3, 6, 9, 0, 0, 5, 6])

In [ ]:
np.r_[-1:1:6j, [0]*2 ,5,6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [ ]:
np.linspace(-1,1,6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [ ]:
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.r_[a,a,a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.r_['0',a,a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.r_['-1',a,a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [ ]:
np.r_['1',a,a]


array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

## 배열분리

In [ ]:
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
s = np.split(x,3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [ ]:
y = np.arange(10, 61, 10)
y

array([10, 20, 30, 40, 50, 60])

In [ ]:
np.split(y, [2,3,4,6])

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int64)]

In [ ]:
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.split(x, [2,6])

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [ ]:
a = np.arange(24).reshape(2,12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
np.split(a,3, axis=1)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [ ]:
np.split(a,4,axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [ ]:
b = np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.split(b, 3, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [ ]:
np.split(b, [2,4,6], axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int64)]

In [ ]:
a = np.arange(24).reshape(2,12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
np.split(a, [3,5,7], axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

In [ ]:
b = np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.split(b,3,axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.hsplit(a,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [ ]:
np.hsplit(a,[2, 5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [ ]:
a = np.arange(24).reshape(2,12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
np.hsplit(a, (3,5,6))

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5],
        [17]]),
 array([[ 6,  7,  8,  9, 10, 11],
        [18, 19, 20, 21, 22, 23]])]

In [ ]:
a[:,:3]

array([[ 0,  1,  2],
       [12, 13, 14]])

In [ ]:
a[:, 8:]

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

In [ ]:
a = np.arange(18).reshape(6,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
np.vsplit(a,3)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [ ]:
a = np.arange(18).reshape(6,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
np.vsplit(a, (1,4,6))

[array([[0, 1, 2]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(0, 3), dtype=int64)]

In [ ]:
a[:1,:]

array([[0, 1, 2]])

In [ ]:
a[4:6,:]

array([[12, 13, 14],
       [15, 16, 17]])

In [ ]:
a[6:,:]

array([], shape=(0, 3), dtype=int64)

In [ ]:
x = np.arange(32).reshape(4,4,2)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
np.split(x,2,axis=0)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [ ]:
np.vsplit(x,2)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [ ]:
x = np.arange(32).reshape(4,4,2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [ ]:
x[:1:,:]

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

In [ ]:
x[1:3]

array([[[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
x[3:]

array([[[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [ ]:
np.vsplit(x, [1,3])

[array([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7]]]),
 array([[[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],
 
        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]]),
 array([[[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [ ]:
x = np.arange(32).reshape(4,4,2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [ ]:
np.hsplit(x,2)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [ ]:
np.split(x,2,axis=1)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [ ]:
x = np.arange(32).reshape(4,4,2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [ ]:
np.hsplit(x, [1, 3])

[array([[[ 0,  1]],
 
        [[ 8,  9]],
 
        [[16, 17]],
 
        [[24, 25]]]),
 array([[[ 2,  3],
         [ 4,  5]],
 
        [[10, 11],
         [12, 13]],
 
        [[18, 19],
         [20, 21]],
 
        [[26, 27],
         [28, 29]]]),
 array([[[ 6,  7]],
 
        [[14, 15]],
 
        [[22, 23]],
 
        [[30, 31]]])]

## numpy의 난수와 다양한 함수

In [ ]:
import numpy as np
rg = np.random.default_rng(12345)
rg.random() #0과1사이에 함수

0.22733602246716966

In [ ]:
r = rg.random(1)
r

array([0.24824571])

In [ ]:
rg.random(5)

array([0.31675834, 0.79736546, 0.67625467, 0.39110955, 0.33281393])

In [ ]:
rg.random((4,3))

array([[0.59830875, 0.18673419, 0.67275604],
       [0.94180287, 0.24824571, 0.94888115],
       [0.66723745, 0.09589794, 0.44183967],
       [0.88647992, 0.6974535 , 0.32647286]])

In [ ]:
rg.random((2,3,4))

array([[[0.73392816, 0.22013496, 0.08159457, 0.1598956 ],
        [0.34010018, 0.46519315, 0.26642103, 0.8157764 ],
        [0.19329439, 0.12946908, 0.09166475, 0.59856801]],

       [[0.8547419 , 0.60162124, 0.93198836, 0.72478136],
        [0.86055132, 0.9293378 , 0.54618601, 0.93767296],
        [0.49498794, 0.27377318, 0.45177871, 0.66503892]]])

In [ ]:
rg  =np.random.default_rng(12345)
r = rg.integers(low=0, high=10, size=3)
r

array([6, 2, 7])

In [ ]:
rg.integers(0, high=20, size=(3,4))

array([[ 6,  4, 15, 12],
       [13, 19,  7, 16],
       [ 6, 11, 11,  4]])

In [ ]:
rg.integers(1,7,(3,4))

array([[2, 2, 5, 4],
       [6, 5, 2, 6],
       [6, 5, 5, 1]])

In [ ]:
rg = np.random.default_rng(1)
rg.standard_normal(5) #표준 정규분포 실수 난수

array([ 0.34558419,  0.82161814,  0.33043708, -1.30315723,  0.90535587])

In [ ]:
rg.standard_normal((3,4))

array([[-0.46674962,  0.23550561,  0.75951952, -1.64878737],
       [ 0.25438812,  1.22464697, -0.29752684, -0.81081458],
       [ 0.75224383,  0.25344652,  0.89588307, -0.34521571]])

In [ ]:
rg = np.random.default_rng(seed=42)
rg.standard_normal(10)

array([ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472, -1.95103519,
       -1.30217951,  0.1278404 , -0.31624259, -0.01680116, -0.85304393])

In [ ]:
rg.standard_normal((4,3))

array([[ 0.87939797,  0.77779194,  0.0660307 ],
       [ 1.12724121,  0.46750934, -0.85929246],
       [ 0.36875078, -0.9588826 ,  0.8784503 ],
       [-0.04992591, -0.18486236, -0.68092954]])

In [ ]:
a= np.arange(1,4)
b= np.arange(4,7)
c= np.arange(7,10)
a,b,c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [ ]:
p= np.arange(1,7).reshape(2,3)
q= np.arange(11,17).reshape(2,3)
w= np.arange(21,27).reshape(2,3)
p,q,w

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [ ]:
np.vstack((a,b,c))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.vstack((p,q,w))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
np.column_stack((a,b,c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate((a,b,c), axis = None)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate((p,q,w))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
np.concatenate((p,q,w), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
np.concatenate((p,q,w), axis=1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
np.concatenate((p,q,w), axis= None)

array([ 1,  2,  3,  4,  5,  6, 11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 25,
       26])

In [ ]:
np.c_[a,b,c] # 20-->20

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.c_[p,q,w] # 20-->20

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.r_[p,q,w]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
np.vstack((p,q,w))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])